make_correct_val(
    0
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_colon, secs"
   ,"2019-01-08T16:50:23"
)
,make_correct_val(
    1
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_colon, msecs"
   ,"2019-01-08T16:50:23.006"
)
,make_correct_val(
    2
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_colon, usecs"
   ,"2019-01-08T16:50:23.006057"
)
,make_correct_val(
    3
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_colon, nsecs"
   ,"2019-01-08T16:50:23.006057057"
)
,make_correct_val(
    4
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_point, secs"
   ,"2019-01-08T16.50.23"
)
,make_correct_val(
    5
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_point, msecs"
   ,"2019-01-08T16.50.23.006"
)
,make_correct_val(
    6
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_point, usecs"
   ,"2019-01-08T16.50.23.006057"
)
,make_correct_val(
    7
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_point, nsecs"
   ,"2019-01-08T16.50.23.006057057"
)
,make_correct_val(
    8
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_empty, secs"
   ,"2019-01-08T165023"
)
,make_correct_val(
    9
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_empty, msecs"
   ,"2019-01-08T165023.006"
)
,make_correct_val(
    10
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_empty, usecs"
   ,"2019-01-08T165023.006057"
)
,make_correct_val(
    11
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_T, time_sep_empty, nsecs"
   ,"2019-01-08T165023.006057057"
)
,make_correct_val(
    12
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_colon, secs"
   ,"2019-01-08t16:50:23"
)
,make_correct_val(
    13
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_colon, msecs"
   ,"2019-01-08t16:50:23.006"
)
,make_correct_val(
    14
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_colon, usecs"
   ,"2019-01-08t16:50:23.006057"
)
,make_correct_val(
    15
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_colon, nsecs"
   ,"2019-01-08t16:50:23.006057057"
)
,make_correct_val(
    16
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_point, secs"
   ,"2019-01-08t16.50.23"
)
,make_correct_val(
    17
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_point, msecs"
   ,"2019-01-08t16.50.23.006"
)
,make_correct_val(
    18
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_point, usecs"
   ,"2019-01-08t16.50.23.006057"
)
,make_correct_val(
    19
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_point, nsecs"
   ,"2019-01-08t16.50.23.006057057"
)
,make_correct_val(
    20
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_empty, secs"
   ,"2019-01-08t165023"
)
,make_correct_val(
    21
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_empty, msecs"
   ,"2019-01-08t165023.006"
)
,make_correct_val(
    22
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_empty, usecs"
   ,"2019-01-08t165023.006057"
)
,make_correct_val(
    23
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_t, time_sep_empty, nsecs"
   ,"2019-01-08t165023.006057057"
)
,make_correct_val(
    24
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_colon, secs"
   ,"2019-01-08 16:50:23"
)
,make_correct_val(
    25
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_colon, msecs"
   ,"2019-01-08 16:50:23.006"
)
,make_correct_val(
    26
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_colon, usecs"
   ,"2019-01-08 16:50:23.006057"
)
,make_correct_val(
    27
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_colon, nsecs"
   ,"2019-01-08 16:50:23.006057057"
)
,make_correct_val(
    28
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_point, secs"
   ,"2019-01-08 16.50.23"
)
,make_correct_val(
    29
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_point, msecs"
   ,"2019-01-08 16.50.23.006"
)
,make_correct_val(
    30
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_point, usecs"
   ,"2019-01-08 16.50.23.006057"
)
,make_correct_val(
    31
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_point, nsecs"
   ,"2019-01-08 16.50.23.006057057"
)
,make_correct_val(
    32
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_empty, secs"
   ,"2019-01-08 165023"
)
,make_correct_val(
    33
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_empty, msecs"
   ,"2019-01-08 165023.006"
)
,make_correct_val(
    34
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_empty, usecs"
   ,"2019-01-08 165023.006057"
)
,make_correct_val(
    35
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_space, time_sep_empty, nsecs"
   ,"2019-01-08 165023.006057057"
)
,make_correct_val(
    36
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_colon, secs"
   ,"2019-01-08_16:50:23"
)
,make_correct_val(
    37
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_colon, msecs"
   ,"2019-01-08_16:50:23.006"
)
,make_correct_val(
    38
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_colon, usecs"
   ,"2019-01-08_16:50:23.006057"
)
,make_correct_val(
    39
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_colon, nsecs"
   ,"2019-01-08_16:50:23.006057057"
)
,make_correct_val(
    40
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_point, secs"
   ,"2019-01-08_16.50.23"
)
,make_correct_val(
    41
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_point, msecs"
   ,"2019-01-08_16.50.23.006"
)
,make_correct_val(
    42
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_point, usecs"
   ,"2019-01-08_16.50.23.006057"
)
,make_correct_val(
    43
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_point, nsecs"
   ,"2019-01-08_16.50.23.006057057"
)
,make_correct_val(
    44
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_empty, secs"
   ,"2019-01-08_165023"
)
,make_correct_val(
    45
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_empty, msecs"
   ,"2019-01-08_165023.006"
)
,make_correct_val(
    46
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_empty, usecs"
   ,"2019-01-08_165023.006057"
)
,make_correct_val(
    47
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_underscore, time_sep_empty, nsecs"
   ,"2019-01-08_165023.006057057"
)
,make_correct_val(
    48
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_colon, secs"
   ,"2019-01-08/16:50:23"
)
,make_correct_val(
    49
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_colon, msecs"
   ,"2019-01-08/16:50:23.006"
)
,make_correct_val(
    50
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_colon, usecs"
   ,"2019-01-08/16:50:23.006057"
)
,make_correct_val(
    51
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_colon, nsecs"
   ,"2019-01-08/16:50:23.006057057"
)
,make_correct_val(
    52
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_point, secs"
   ,"2019-01-08/16.50.23"
)
,make_correct_val(
    53
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_point, msecs"
   ,"2019-01-08/16.50.23.006"
)
,make_correct_val(
    54
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_point, usecs"
   ,"2019-01-08/16.50.23.006057"
)
,make_correct_val(
    55
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_point, nsecs"
   ,"2019-01-08/16.50.23.006057057"
)
,make_correct_val(
    56
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_empty, secs"
   ,"2019-01-08/165023"
)
,make_correct_val(
    57
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_empty, msecs"
   ,"2019-01-08/165023.006"
)
,make_correct_val(
    58
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_empty, usecs"
   ,"2019-01-08/165023.006057"
)
,make_correct_val(
    59
   ,dtf::yyyy_mm_dd | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_dash, dt_sep_slash, time_sep_empty, nsecs"
   ,"2019-01-08/165023.006057057"
)
,make_correct_val(
    60
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_colon, secs"
   ,"2019.01.08T16:50:23"
)
,make_correct_val(
    61
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_colon, msecs"
   ,"2019.01.08T16:50:23.006"
)
,make_correct_val(
    62
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_colon, usecs"
   ,"2019.01.08T16:50:23.006057"
)
,make_correct_val(
    63
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_colon, nsecs"
   ,"2019.01.08T16:50:23.006057057"
)
,make_correct_val(
    64
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_point, secs"
   ,"2019.01.08T16.50.23"
)
,make_correct_val(
    65
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_point, msecs"
   ,"2019.01.08T16.50.23.006"
)
,make_correct_val(
    66
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_point, usecs"
   ,"2019.01.08T16.50.23.006057"
)
,make_correct_val(
    67
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_point, nsecs"
   ,"2019.01.08T16.50.23.006057057"
)
,make_correct_val(
    68
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_empty, secs"
   ,"2019.01.08T165023"
)
,make_correct_val(
    69
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_empty, msecs"
   ,"2019.01.08T165023.006"
)
,make_correct_val(
    70
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_empty, usecs"
   ,"2019.01.08T165023.006057"
)
,make_correct_val(
    71
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_T, time_sep_empty, nsecs"
   ,"2019.01.08T165023.006057057"
)
,make_correct_val(
    72
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_colon, secs"
   ,"2019.01.08t16:50:23"
)
,make_correct_val(
    73
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_colon, msecs"
   ,"2019.01.08t16:50:23.006"
)
,make_correct_val(
    74
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_colon, usecs"
   ,"2019.01.08t16:50:23.006057"
)
,make_correct_val(
    75
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_colon, nsecs"
   ,"2019.01.08t16:50:23.006057057"
)
,make_correct_val(
    76
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_point, secs"
   ,"2019.01.08t16.50.23"
)
,make_correct_val(
    77
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_point, msecs"
   ,"2019.01.08t16.50.23.006"
)
,make_correct_val(
    78
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_point, usecs"
   ,"2019.01.08t16.50.23.006057"
)
,make_correct_val(
    79
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_point, nsecs"
   ,"2019.01.08t16.50.23.006057057"
)
,make_correct_val(
    80
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_empty, secs"
   ,"2019.01.08t165023"
)
,make_correct_val(
    81
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_empty, msecs"
   ,"2019.01.08t165023.006"
)
,make_correct_val(
    82
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_empty, usecs"
   ,"2019.01.08t165023.006057"
)
,make_correct_val(
    83
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_t, time_sep_empty, nsecs"
   ,"2019.01.08t165023.006057057"
)
,make_correct_val(
    84
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_colon, secs"
   ,"2019.01.08 16:50:23"
)
,make_correct_val(
    85
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_colon, msecs"
   ,"2019.01.08 16:50:23.006"
)
,make_correct_val(
    86
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_colon, usecs"
   ,"2019.01.08 16:50:23.006057"
)
,make_correct_val(
    87
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_colon, nsecs"
   ,"2019.01.08 16:50:23.006057057"
)
,make_correct_val(
    88
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_point, secs"
   ,"2019.01.08 16.50.23"
)
,make_correct_val(
    89
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_point, msecs"
   ,"2019.01.08 16.50.23.006"
)
,make_correct_val(
    90
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_point, usecs"
   ,"2019.01.08 16.50.23.006057"
)
,make_correct_val(
    91
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_point, nsecs"
   ,"2019.01.08 16.50.23.006057057"
)
,make_correct_val(
    92
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_empty, secs"
   ,"2019.01.08 165023"
)
,make_correct_val(
    93
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_empty, msecs"
   ,"2019.01.08 165023.006"
)
,make_correct_val(
    94
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_empty, usecs"
   ,"2019.01.08 165023.006057"
)
,make_correct_val(
    95
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_space, time_sep_empty, nsecs"
   ,"2019.01.08 165023.006057057"
)
,make_correct_val(
    96
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_colon, secs"
   ,"2019.01.08_16:50:23"
)
,make_correct_val(
    97
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_colon, msecs"
   ,"2019.01.08_16:50:23.006"
)
,make_correct_val(
    98
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_colon, usecs"
   ,"2019.01.08_16:50:23.006057"
)
,make_correct_val(
    99
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_colon, nsecs"
   ,"2019.01.08_16:50:23.006057057"
)
,make_correct_val(
    100
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_point, secs"
   ,"2019.01.08_16.50.23"
)
,make_correct_val(
    101
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_point, msecs"
   ,"2019.01.08_16.50.23.006"
)
,make_correct_val(
    102
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_point, usecs"
   ,"2019.01.08_16.50.23.006057"
)
,make_correct_val(
    103
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_point, nsecs"
   ,"2019.01.08_16.50.23.006057057"
)
,make_correct_val(
    104
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_empty, secs"
   ,"2019.01.08_165023"
)
,make_correct_val(
    105
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_empty, msecs"
   ,"2019.01.08_165023.006"
)
,make_correct_val(
    106
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_empty, usecs"
   ,"2019.01.08_165023.006057"
)
,make_correct_val(
    107
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_underscore, time_sep_empty, nsecs"
   ,"2019.01.08_165023.006057057"
)
,make_correct_val(
    108
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_colon, secs"
   ,"2019.01.08/16:50:23"
)
,make_correct_val(
    109
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_colon, msecs"
   ,"2019.01.08/16:50:23.006"
)
,make_correct_val(
    110
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_colon, usecs"
   ,"2019.01.08/16:50:23.006057"
)
,make_correct_val(
    111
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_colon, nsecs"
   ,"2019.01.08/16:50:23.006057057"
)
,make_correct_val(
    112
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_point, secs"
   ,"2019.01.08/16.50.23"
)
,make_correct_val(
    113
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_point, msecs"
   ,"2019.01.08/16.50.23.006"
)
,make_correct_val(
    114
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_point, usecs"
   ,"2019.01.08/16.50.23.006057"
)
,make_correct_val(
    115
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_point, nsecs"
   ,"2019.01.08/16.50.23.006057057"
)
,make_correct_val(
    116
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_empty, secs"
   ,"2019.01.08/165023"
)
,make_correct_val(
    117
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_empty, msecs"
   ,"2019.01.08/165023.006"
)
,make_correct_val(
    118
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_empty, usecs"
   ,"2019.01.08/165023.006057"
)
,make_correct_val(
    119
   ,dtf::yyyy_mm_dd | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_point, dt_sep_slash, time_sep_empty, nsecs"
   ,"2019.01.08/165023.006057057"
)
,make_correct_val(
    120
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_colon | dtf::secs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_colon, secs"
   ,"20190108T16:50:23"
)
,make_correct_val(
    121
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_colon | dtf::msecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_colon, msecs"
   ,"20190108T16:50:23.006"
)
,make_correct_val(
    122
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_colon | dtf::usecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_colon, usecs"
   ,"20190108T16:50:23.006057"
)
,make_correct_val(
    123
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_colon | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_colon, nsecs"
   ,"20190108T16:50:23.006057057"
)
,make_correct_val(
    124
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_point | dtf::secs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_point, secs"
   ,"20190108T16.50.23"
)
,make_correct_val(
    125
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_point | dtf::msecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_point, msecs"
   ,"20190108T16.50.23.006"
)
,make_correct_val(
    126
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_point | dtf::usecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_point, usecs"
   ,"20190108T16.50.23.006057"
)
,make_correct_val(
    127
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_point | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_point, nsecs"
   ,"20190108T16.50.23.006057057"
)
,make_correct_val(
    128
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_empty | dtf::secs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_empty, secs"
   ,"20190108T165023"
)
,make_correct_val(
    129
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_empty | dtf::msecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_empty, msecs"
   ,"20190108T165023.006"
)
,make_correct_val(
    130
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_empty | dtf::usecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_empty, usecs"
   ,"20190108T165023.006057"
)
,make_correct_val(
    131
   ,dtf::yyyy_mm_dd | dtf::date_sep_empty | dtf::dt_sep_T | dtf::time_sep_empty | dtf::nsecs
   ,"yyyy_mm_dd, date_sep_empty, dt_sep_T, time_sep_empty, nsecs"
   ,"20190108T165023.006057057"
)
,make_correct_val(
    132
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_colon, secs"
   ,"08-01-2019T16:50:23"
)
,make_correct_val(
    133
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_colon, msecs"
   ,"08-01-2019T16:50:23.006"
)
,make_correct_val(
    134
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_colon, usecs"
   ,"08-01-2019T16:50:23.006057"
)
,make_correct_val(
    135
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_colon, nsecs"
   ,"08-01-2019T16:50:23.006057057"
)
,make_correct_val(
    136
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_point, secs"
   ,"08-01-2019T16.50.23"
)
,make_correct_val(
    137
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_point, msecs"
   ,"08-01-2019T16.50.23.006"
)
,make_correct_val(
    138
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_point, usecs"
   ,"08-01-2019T16.50.23.006057"
)
,make_correct_val(
    139
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_point, nsecs"
   ,"08-01-2019T16.50.23.006057057"
)
,make_correct_val(
    140
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_empty, secs"
   ,"08-01-2019T165023"
)
,make_correct_val(
    141
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_empty, msecs"
   ,"08-01-2019T165023.006"
)
,make_correct_val(
    142
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_empty, usecs"
   ,"08-01-2019T165023.006057"
)
,make_correct_val(
    143
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_T | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_T, time_sep_empty, nsecs"
   ,"08-01-2019T165023.006057057"
)
,make_correct_val(
    144
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_colon, secs"
   ,"08-01-2019t16:50:23"
)
,make_correct_val(
    145
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_colon, msecs"
   ,"08-01-2019t16:50:23.006"
)
,make_correct_val(
    146
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_colon, usecs"
   ,"08-01-2019t16:50:23.006057"
)
,make_correct_val(
    147
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_colon, nsecs"
   ,"08-01-2019t16:50:23.006057057"
)
,make_correct_val(
    148
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_point, secs"
   ,"08-01-2019t16.50.23"
)
,make_correct_val(
    149
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_point, msecs"
   ,"08-01-2019t16.50.23.006"
)
,make_correct_val(
    150
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_point, usecs"
   ,"08-01-2019t16.50.23.006057"
)
,make_correct_val(
    151
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_point, nsecs"
   ,"08-01-2019t16.50.23.006057057"
)
,make_correct_val(
    152
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_empty, secs"
   ,"08-01-2019t165023"
)
,make_correct_val(
    153
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_empty, msecs"
   ,"08-01-2019t165023.006"
)
,make_correct_val(
    154
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_empty, usecs"
   ,"08-01-2019t165023.006057"
)
,make_correct_val(
    155
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_t | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_t, time_sep_empty, nsecs"
   ,"08-01-2019t165023.006057057"
)
,make_correct_val(
    156
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_colon, secs"
   ,"08-01-2019 16:50:23"
)
,make_correct_val(
    157
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_colon, msecs"
   ,"08-01-2019 16:50:23.006"
)
,make_correct_val(
    158
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_colon, usecs"
   ,"08-01-2019 16:50:23.006057"
)
,make_correct_val(
    159
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_colon, nsecs"
   ,"08-01-2019 16:50:23.006057057"
)
,make_correct_val(
    160
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_point, secs"
   ,"08-01-2019 16.50.23"
)
,make_correct_val(
    161
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_point, msecs"
   ,"08-01-2019 16.50.23.006"
)
,make_correct_val(
    162
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_point, usecs"
   ,"08-01-2019 16.50.23.006057"
)
,make_correct_val(
    163
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_point, nsecs"
   ,"08-01-2019 16.50.23.006057057"
)
,make_correct_val(
    164
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_empty, secs"
   ,"08-01-2019 165023"
)
,make_correct_val(
    165
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_empty, msecs"
   ,"08-01-2019 165023.006"
)
,make_correct_val(
    166
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_empty, usecs"
   ,"08-01-2019 165023.006057"
)
,make_correct_val(
    167
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_space | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_space, time_sep_empty, nsecs"
   ,"08-01-2019 165023.006057057"
)
,make_correct_val(
    168
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_colon, secs"
   ,"08-01-2019_16:50:23"
)
,make_correct_val(
    169
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_colon, msecs"
   ,"08-01-2019_16:50:23.006"
)
,make_correct_val(
    170
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_colon, usecs"
   ,"08-01-2019_16:50:23.006057"
)
,make_correct_val(
    171
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_colon, nsecs"
   ,"08-01-2019_16:50:23.006057057"
)
,make_correct_val(
    172
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_point, secs"
   ,"08-01-2019_16.50.23"
)
,make_correct_val(
    173
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_point, msecs"
   ,"08-01-2019_16.50.23.006"
)
,make_correct_val(
    174
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_point, usecs"
   ,"08-01-2019_16.50.23.006057"
)
,make_correct_val(
    175
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_point, nsecs"
   ,"08-01-2019_16.50.23.006057057"
)
,make_correct_val(
    176
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_empty, secs"
   ,"08-01-2019_165023"
)
,make_correct_val(
    177
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_empty, msecs"
   ,"08-01-2019_165023.006"
)
,make_correct_val(
    178
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_empty, usecs"
   ,"08-01-2019_165023.006057"
)
,make_correct_val(
    179
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_underscore, time_sep_empty, nsecs"
   ,"08-01-2019_165023.006057057"
)
,make_correct_val(
    180
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_colon, secs"
   ,"08-01-2019/16:50:23"
)
,make_correct_val(
    181
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_colon, msecs"
   ,"08-01-2019/16:50:23.006"
)
,make_correct_val(
    182
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_colon, usecs"
   ,"08-01-2019/16:50:23.006057"
)
,make_correct_val(
    183
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_colon, nsecs"
   ,"08-01-2019/16:50:23.006057057"
)
,make_correct_val(
    184
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_point, secs"
   ,"08-01-2019/16.50.23"
)
,make_correct_val(
    185
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_point, msecs"
   ,"08-01-2019/16.50.23.006"
)
,make_correct_val(
    186
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_point, usecs"
   ,"08-01-2019/16.50.23.006057"
)
,make_correct_val(
    187
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_point, nsecs"
   ,"08-01-2019/16.50.23.006057057"
)
,make_correct_val(
    188
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_empty, secs"
   ,"08-01-2019/165023"
)
,make_correct_val(
    189
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_empty, msecs"
   ,"08-01-2019/165023.006"
)
,make_correct_val(
    190
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_empty, usecs"
   ,"08-01-2019/165023.006057"
)
,make_correct_val(
    191
   ,dtf::dd_mm_yyyy | dtf::date_sep_dash | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_dash, dt_sep_slash, time_sep_empty, nsecs"
   ,"08-01-2019/165023.006057057"
)
,make_correct_val(
    192
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_colon, secs"
   ,"08.01.2019T16:50:23"
)
,make_correct_val(
    193
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_colon, msecs"
   ,"08.01.2019T16:50:23.006"
)
,make_correct_val(
    194
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_colon, usecs"
   ,"08.01.2019T16:50:23.006057"
)
,make_correct_val(
    195
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_colon, nsecs"
   ,"08.01.2019T16:50:23.006057057"
)
,make_correct_val(
    196
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_point, secs"
   ,"08.01.2019T16.50.23"
)
,make_correct_val(
    197
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_point, msecs"
   ,"08.01.2019T16.50.23.006"
)
,make_correct_val(
    198
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_point, usecs"
   ,"08.01.2019T16.50.23.006057"
)
,make_correct_val(
    199
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_point, nsecs"
   ,"08.01.2019T16.50.23.006057057"
)
,make_correct_val(
    200
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_empty, secs"
   ,"08.01.2019T165023"
)
,make_correct_val(
    201
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_empty, msecs"
   ,"08.01.2019T165023.006"
)
,make_correct_val(
    202
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_empty, usecs"
   ,"08.01.2019T165023.006057"
)
,make_correct_val(
    203
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_T | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_T, time_sep_empty, nsecs"
   ,"08.01.2019T165023.006057057"
)
,make_correct_val(
    204
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_colon, secs"
   ,"08.01.2019t16:50:23"
)
,make_correct_val(
    205
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_colon, msecs"
   ,"08.01.2019t16:50:23.006"
)
,make_correct_val(
    206
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_colon, usecs"
   ,"08.01.2019t16:50:23.006057"
)
,make_correct_val(
    207
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_colon, nsecs"
   ,"08.01.2019t16:50:23.006057057"
)
,make_correct_val(
    208
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_point, secs"
   ,"08.01.2019t16.50.23"
)
,make_correct_val(
    209
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_point, msecs"
   ,"08.01.2019t16.50.23.006"
)
,make_correct_val(
    210
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_point, usecs"
   ,"08.01.2019t16.50.23.006057"
)
,make_correct_val(
    211
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_point, nsecs"
   ,"08.01.2019t16.50.23.006057057"
)
,make_correct_val(
    212
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_empty, secs"
   ,"08.01.2019t165023"
)
,make_correct_val(
    213
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_empty, msecs"
   ,"08.01.2019t165023.006"
)
,make_correct_val(
    214
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_empty, usecs"
   ,"08.01.2019t165023.006057"
)
,make_correct_val(
    215
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_t | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_t, time_sep_empty, nsecs"
   ,"08.01.2019t165023.006057057"
)
,make_correct_val(
    216
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_colon, secs"
   ,"08.01.2019 16:50:23"
)
,make_correct_val(
    217
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_colon, msecs"
   ,"08.01.2019 16:50:23.006"
)
,make_correct_val(
    218
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_colon, usecs"
   ,"08.01.2019 16:50:23.006057"
)
,make_correct_val(
    219
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_colon, nsecs"
   ,"08.01.2019 16:50:23.006057057"
)
,make_correct_val(
    220
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_point, secs"
   ,"08.01.2019 16.50.23"
)
,make_correct_val(
    221
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_point, msecs"
   ,"08.01.2019 16.50.23.006"
)
,make_correct_val(
    222
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_point, usecs"
   ,"08.01.2019 16.50.23.006057"
)
,make_correct_val(
    223
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_point, nsecs"
   ,"08.01.2019 16.50.23.006057057"
)
,make_correct_val(
    224
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_empty, secs"
   ,"08.01.2019 165023"
)
,make_correct_val(
    225
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_empty, msecs"
   ,"08.01.2019 165023.006"
)
,make_correct_val(
    226
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_empty, usecs"
   ,"08.01.2019 165023.006057"
)
,make_correct_val(
    227
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_space | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_space, time_sep_empty, nsecs"
   ,"08.01.2019 165023.006057057"
)
,make_correct_val(
    228
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_colon, secs"
   ,"08.01.2019_16:50:23"
)
,make_correct_val(
    229
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_colon, msecs"
   ,"08.01.2019_16:50:23.006"
)
,make_correct_val(
    230
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_colon, usecs"
   ,"08.01.2019_16:50:23.006057"
)
,make_correct_val(
    231
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_colon, nsecs"
   ,"08.01.2019_16:50:23.006057057"
)
,make_correct_val(
    232
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_point, secs"
   ,"08.01.2019_16.50.23"
)
,make_correct_val(
    233
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_point, msecs"
   ,"08.01.2019_16.50.23.006"
)
,make_correct_val(
    234
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_point, usecs"
   ,"08.01.2019_16.50.23.006057"
)
,make_correct_val(
    235
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_point, nsecs"
   ,"08.01.2019_16.50.23.006057057"
)
,make_correct_val(
    236
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_empty, secs"
   ,"08.01.2019_165023"
)
,make_correct_val(
    237
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_empty, msecs"
   ,"08.01.2019_165023.006"
)
,make_correct_val(
    238
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_empty, usecs"
   ,"08.01.2019_165023.006057"
)
,make_correct_val(
    239
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_underscore | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_underscore, time_sep_empty, nsecs"
   ,"08.01.2019_165023.006057057"
)
,make_correct_val(
    240
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_colon, secs"
   ,"08.01.2019/16:50:23"
)
,make_correct_val(
    241
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_colon, msecs"
   ,"08.01.2019/16:50:23.006"
)
,make_correct_val(
    242
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_colon, usecs"
   ,"08.01.2019/16:50:23.006057"
)
,make_correct_val(
    243
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_colon, nsecs"
   ,"08.01.2019/16:50:23.006057057"
)
,make_correct_val(
    244
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_point, secs"
   ,"08.01.2019/16.50.23"
)
,make_correct_val(
    245
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_point, msecs"
   ,"08.01.2019/16.50.23.006"
)
,make_correct_val(
    246
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_point, usecs"
   ,"08.01.2019/16.50.23.006057"
)
,make_correct_val(
    247
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_point, nsecs"
   ,"08.01.2019/16.50.23.006057057"
)
,make_correct_val(
    248
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_empty, secs"
   ,"08.01.2019/165023"
)
,make_correct_val(
    249
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_empty, msecs"
   ,"08.01.2019/165023.006"
)
,make_correct_val(
    250
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_empty, usecs"
   ,"08.01.2019/165023.006057"
)
,make_correct_val(
    251
   ,dtf::dd_mm_yyyy | dtf::date_sep_point | dtf::dt_sep_slash | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_point, dt_sep_slash, time_sep_empty, nsecs"
   ,"08.01.2019/165023.006057057"
)
,make_correct_val(
    252
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_colon | dtf::secs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_colon, secs"
   ,"08012019t16:50:23"
)
,make_correct_val(
    253
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_colon | dtf::msecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_colon, msecs"
   ,"08012019t16:50:23.006"
)
,make_correct_val(
    254
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_colon | dtf::usecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_colon, usecs"
   ,"08012019t16:50:23.006057"
)
,make_correct_val(
    255
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_colon | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_colon, nsecs"
   ,"08012019t16:50:23.006057057"
)
,make_correct_val(
    256
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_point | dtf::secs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_point, secs"
   ,"08012019t16.50.23"
)
,make_correct_val(
    257
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_point | dtf::msecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_point, msecs"
   ,"08012019t16.50.23.006"
)
,make_correct_val(
    258
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_point | dtf::usecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_point, usecs"
   ,"08012019t16.50.23.006057"
)
,make_correct_val(
    259
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_point | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_point, nsecs"
   ,"08012019t16.50.23.006057057"
)
,make_correct_val(
    260
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_empty | dtf::secs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_empty, secs"
   ,"08012019t165023"
)
,make_correct_val(
    261
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_empty | dtf::msecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_empty, msecs"
   ,"08012019t165023.006"
)
,make_correct_val(
    262
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_empty | dtf::usecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_empty, usecs"
   ,"08012019t165023.006057"
)
,make_correct_val(
    263
   ,dtf::dd_mm_yyyy | dtf::date_sep_empty | dtf::dt_sep_t | dtf::time_sep_empty | dtf::nsecs
   ,"dd_mm_yyyy, date_sep_empty, dt_sep_t, time_sep_empty, nsecs"
   ,"08012019t165023.006057057"
)
